Parameters:
  VPCName: 
    Description: VPC name
    Type: String
    Default: vpc-x
  Tag:
    Description: Tag
    Type: "String"
  DBInstanceIdentifier:
    Description: RDS instance name
    Type: String
    Default: "database-x"
  DBName:
    Description: PostgeSQL database name
    Type: "String"
    Default: "postgres"
  DBUsername:
    Description: PostgreSQL username
    Type: "String"
    Default: "postgres"
  DBPassword:
    Description: PostgreSQL password
    Type: "String"
    Default: "postgres"

Resources: 
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      Tags:
      - Key: "Name"
        Value: !Ref VPCName

  SubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
        - 0
        - !GetAZs 
          Ref: AWS::Region
      VpcId: !Ref VPC
      CidrBlock: "10.0.0.0/24"

  SubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
        - 1
        - !GetAZs 
          Ref: AWS::Region
      VpcId: !Ref VPC
      CidrBlock: "10.0.1.0/24"

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  SubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: "rds-subnet-group"
      DBSubnetGroupDescription: "RDS subnet group"
      SubnetIds:
      - !Ref SubnetA
      - !Ref SubnetB

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "rds-ec2-sg"
      GroupDescription: "Allow RDS traffic"
      VpcId: !Ref VPC
      SecurityGroupEgress:
      - IpProtocol: "-1"
        CidrIp: "0.0.0.0/0"

  InstanceSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    DependsOn: InstanceSecurityGroup
    Properties:
      GroupId: !Ref InstanceSecurityGroup
      IpProtocol: "tcp"
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref InstanceSecurityGroup

  Instance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSubnetGroupName: !Ref SubnetGroup
      VPCSecurityGroups:
        - !Ref InstanceSecurityGroup
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBInstanceClass: db.t3.micro
      AllocatedStorage: "5"
      Engine: postgres
      EngineVersion: "15.2"
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      Tags:
        - Key: Name
          Value: !Ref Tag
    UpdateReplacePolicy: Snapshot
    DeletionPolicy: Delete

Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref VPC